- hosts: jenkins
  sudo: yes
  vars_files:
    - vars.yml
  roles:
    - { role: common, tags: common }
    - { role: docker, tags: docker }
  tasks:
    - name: "Add docker group to current user"
      shell: usermod -G docker -a {{ ssh_user }}

    - name: "Create /var/data"
      file: state=directory path=/var/data/www/html owner={{ ssh_user }} mode=0777

    - name: "Start mysql container"
      docker:
        state: running
        name: "mysql"
        image: "mysql"
        ports: "3306:3306"
        env: "MYSQL_ROOT_PASSWORD={{ mysql_root_password }}"
        volumes:
          - "/var/data/mysql:/var/lib/mysql"
      tags: mysql

    - name: "Start web production container"
      docker:
        state: running
        name: "web-prod"
        image: "yoshz/apache-php"
        ports: 
          - "8022:22"
          - "8000:80"
        volumes:
          - "/var/data/prod:/var/www"
        links:
          - "mysql:db"
        env: "USER_CREATE=deploy,USER_PASSWORD=deploy"
      tags: apache

    - name: Configure firewall for Apache
      ufw: rule=allow port=8000 proto=tcp
      tags: apache

    - name: "Start web jenkins slave container"
      docker:
        state: running
        name: "web-slave"
        image: "yoshz/apache-php-dev"
        ports:
          - "3022:22"
          - "3000:80"
        volumes:
          - "/var/data/dev:/var/www"
        links:
          - "mysql:db"
          - "web-prod"
        env: "USER_CREATE=jenkins,USER_PASSWORD=jenkins,GIT_NAME=jenkins,GIT_EMAIL=jenkins"
      tags: apache

    - name: "Start Jenkins docker container"
      docker:
        state: running
        name: "jenkins"
        image: "jenkins:weekly"
        ports: "8080:8080"
        privileged: yes
        links:
          - "web-slave"
      tags: jenkins

    - name: Configure firewall for Jenkins
      ufw: rule=allow port=8080 proto=tcp
      tags: jenkins

