- hosts: jenkins
  sudo: yes
  vars_files:
    - vars.yml
  roles:
    - { role: common, tags: common }
    - { role: docker, tags: docker }
    - { role: jenkins, tags: jenkins }
  tasks:
    - name: "Add docker group to current user"
      shell: usermod -G docker -a {{ ssh_user }}

    - name: "Start mysql production container"
      docker:
        state: running
        name: "mysql-prod"
        image: "mysql"
        ports: "8306:3306"
        env: "MYSQL_ROOT_PASSWORD={{ mysql_root_password }}"
        volumes:
          - "/var/data/mysql-prod:/var/lib/mysql"
      tags: container

    - name: "Start mysql staging container"
      docker:
        state: running
        name: "mysql-staging"
        image: "mysql"
        ports: "7306:3306"
        env: "MYSQL_ROOT_PASSWORD={{ mysql_root_password }}"
        volumes:
          - "/var/data/mysql-staging:/var/lib/mysql"
      tags: container

    - name: "Start web production container"
      docker:
        state: running
        name: "web-prod"
        image: "yoshz/apache-php"
        ports: 
          - "8022:22"
          - "8000:80"
        volumes:
          - "/var/data/prod:/var/www"
        links:
          - "mysql-prod:db"
        env: "USER_CREATE=deploy,USER_PUBLIC_KEY=\"{{ deploy_public_key }}\""
      tags: container
    - name: Configure firewall for Apache
      ufw: rule=allow port=8000 proto=tcp
      tags: firewall

    - name: "Start web staging container"
      docker:
        state: running
        name: "web-staging"
        image: "yoshz/apache-php"
        ports: 
          - "7022:22"
          - "7000:80"
        volumes:
          - "/var/data/staging:/var/www"
        links:
          - "mysql-staging:db"
        env: "USER_CREATE=deploy,USER_PUBLIC_KEY=\"{{ deploy_public_key }}\""
      tags: container
    - name: Configure firewall for Apache
      ufw: rule=allow port=7000 proto=tcp
      tags: firewall

    - name: "Start web dev container"
      docker:
        state: running
        name: "web-dev"
        image: "yoshz/apache-php-dev"
        ports:
          - "3022:22"
          - "3000:80"
        volumes:
          - "/var/data/dev:/var/www"
        links:
          - "web-staging"
          - "web-prod"
        env: "USER_CREATE=deploy,USER_PUBLIC_KEY=\"{{ deploy_public_key }}\",GIT_NAME=jenkins,GIT_EMAIL=jenkins"
      tags: container

    - name: Configure firewall for Jenkins
      ufw: rule=allow port=8080 proto=tcp
      tags: firewall

