- hosts: jenkins
  sudo: yes
  vars_files:
    - ../vars.yml
  tasks:
    - name: "Install boto python package"
      pip: name=boto

    - name: "Create backup directory"
      file: path=/tmp/backup state=directory

    - name: "Upload restore script"
      copy: src=../files/jenkins-restore.sh dest=/tmp/backup/jenkins-restore.sh mode=0755

    - name: "Download backup file from S3"
      s3: bucket={{ s3_backup_bucket }} aws_access_key={{ aws_access_key }} aws_secret_key={{ aws_secret_key }} object=/jenkins-backup-latest.tar.gz dest=/tmp/backup/jenkins-backup-latest.tar.gz mode=get

    - name: "Restore jenkins home directory"
      shell: /tmp/backup/jenkins-restore.sh /var/lib/jenkins /tmp/backup/jenkins-backup-latest.tar.gz

    - name: "Restore ownership"
      shell: chown jenkins.jenkins -R /var/lib/jenkins

    - name: "Remove backup file"
      file: path=/tmp/backup/jenkins-backup-latest.tar.gz state=absent

    - name: "Restart jenkins"
      service: name=jenkins state=restarted
